name:                p4h
version:             2023.1
github:              "githubuser/p4h"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/p4h#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- bytestring
- inline-c
- inline-c-cpp

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  cxx-sources:
  - cbits/hsclientuser.cc
  - cbits/hsclientapi.cc
  - cbits/hsspecdata.cpp
  - cbits/specmgr.cpp
  cxx-options:
  - -DP4API_VERSION=513538 -std=c++11 -Wall

executables:
  p4h-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl-lclient
    - -optl-lp4api
    - -optl-lrpc
    - -optl-lssl
    - -optl-lcrypto
    - -optl-lsupp
    when:
    - condition: os(linux)
      ghc-options:
      - -optl-Wl,--allow-multiple-definition
      extra-lib-dirs:
      - ./p4api/lib_linux
    - condition: os(darwin)
      extra-lib-dirs:
      - ./p4api/lib_macos
      frameworks:
      - Foundation
      - AppKit
      - Security
    dependencies:
    - p4h

tests:
  p4h-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - p4h
